### ISSUE TITLE
can't create the model with the config file

### ISSUE THREAD

**Issue by ConanCui** [peiyunh/wysiwyg#2]
Hi I run the training script with the config, 
and it shows that there is a typo in the config that "rpn" is spelled with "vpn"
https://github.com/peiyunh/wysiwyg/blob/b1747a2aceb26bccfaeb825e0cac4b21f87eeb1e/second/configs/nuscenes/all.pp.mhead.vpn.config#L32

I correct it and run the train script with the config, and it still shows the error as below, could you tell that why would this happen?

`Traceback (most recent call last):
  File "script.py", line 141, in <module>
    fire.Fire()
  File "/DATA3_DB7/data/kncui/miniconda3/envs/Lidar/lib/python3.6/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/DATA3_DB7/data/kncui/miniconda3/envs/Lidar/lib/python3.6/site-packages/fire/core.py", line 468, in _Fire
    target=component.__name__)
  File "/DATA3_DB7/data/kncui/miniconda3/envs/Lidar/lib/python3.6/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "script.py", line 138, in test_nuscenes
    evaluate(cfg, model_dir, ckpt_path=ckpt_path, clean_after=False)
  File "/DATA3_DB7/data/kncui/wysiwyg/second/pytorch/train.py", line 479, in evaluate
    net = build_network(model_cfg, measure_time=measure_time).to(device)
  File "/DATA3_DB7/data/kncui/wysiwyg/second/pytorch/train.py", line 73, in build_network
    model_cfg, voxel_generator, target_assigner, measure_time=measure_time)
  File "/DATA3_DB7/data/kncui/wysiwyg/second/pytorch/builder/second_builder.py", line 142, in build
    direction_limit_offset=model_cfg.direction_limit_offset,
  File "/DATA3_DB7/data/kncui/wysiwyg/second/pytorch/models/net_multi_head.py", line 275, in __init__
    super().__init__(*args, **kw)
  File "/DATA3_DB7/data/kncui/wysiwyg/second/pytorch/models/voxelnet.py", line 182, in __init__
    num_direction_bins=self._num_direction_bins)
  File "/DATA3_DB7/data/kncui/wysiwyg/second/pytorch/models/rpn.py", line 242, in __init__
    assert val == must_equal_list[0]
AssertionError
`

**Comment by peiyunh** [comment]
In fact it is not a typo - v for visibility. Please let me know if the error persists after you revert the change.

**Comment by ConanCui** [comment]
Thanks for your kindly reply.
There are no error after your exlaination. And I still have some equestion about the training.
1. I download the training model weight from your google drive link and its name shows  “voxelnet-187540”, how long dose it need to train on a Titan 1080 GPU by your experience? could I continue to fintune the model with this weight?

2. I notice that the creation of nuscene data in your codes show some difference with the second.pytorch repo. What is noticeable is that the "sweep_db" configure paramrter. What dose this parameters means? What's the effect it has on the training and data creation? 
3. could you share that how to visualize?

**Comment by peiyunh** [comment]
Sorry for the late response. 

1. I don't remember exactly but it probably took me a few days to train the released model on the full training set though I develop on much smaller subsets. Importantly, I was training on a single GTX 2080 card. 

2. I think I answered this question in #4. 

3. For visualization, I modified SECOND's kittiviewer after learning a bare minimum of threes. I do hope to share the visualization code, but I don't know when I will get to clean it up for release.
